version: "3"
services:
    node-expense:
        build: .
        ports:
            - "3002:3002"
        #volumes:
        #    - ./:/app
        environment: 
            - PORT=3002  
        depends_on:
            - mongo                     
    mongo:
        image: mongo 
        environment:
            - MONGO_INITDB_ROOT_USERNAME=kkmouf 
            - MONGO_INITDB_ROOT_PASSWORD=123456      