image:
  repository: kkryptocode/ecommerce
  tag: 0.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  externalPort: 3002
  internalPort: 3002
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

ingress:
  host: ecommerce-app-1.devopsk.com

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpuTargetAverageUtilization: 80
  memoryTargetAverageUtilization: 80

istio:
  enabled: false

ecommerce-app-1-db:
  replicaSet:
    enabled: true
